swagger: "2.0"
produces:
- application/json
schemes:
- http
consumes:
- application/json
info:
  contact:
    email: ivan@flanders.co.nz
    name: Ivan Porto Carrero
  description: K/V store is a simple single node store for retrieving key/value information
  license:
    name: MIT
    url: https://github.com/go-openapi/kvstore/blob/master/LICENSE
  title: K/V store
  version: 0.0.1

parameters:
  requestId:
    name: X-Request-Id
    description: A unique UUID for the request
    in: header
    type: string
    required: false
    minLength: 1
  entryKey:
    name: key
    description: The key for a given entry
    in: path
    type: string
    required: true
    minLength: 1

responses:
  errorNotFound:
    description: The entry was not found
    headers:
      X-Request-Id:
        description: The request id this is a response to
        type: string
    schema:
      $ref: '#/definitions/error'
  errorResponse:
    description: Error
    headers:
      X-Request-Id:
        description: The request id this is a response to
        type: string
    schema:
      $ref: '#/definitions/error'

paths:
  /kv:
    parameters:
      - $ref: "#/parameters/requestId"
    get:
      operationId: findKeys
      tags:
      - kv
      description: lists all the keys
      parameters:
        - name: prefix
          in: query
          type: string
      responses:
        200:
          description: list the keys known to this datastore
          headers:
            X-Request-Id:
              description: The request id this is a response to
              type: string
          schema:
            type: array
            items:
              type: string
        default:
          $ref: "#/responses/errorResponse"

  /kv/{key}:
    parameters:
      - $ref: "#/parameters/requestId"
      - $ref: "#/parameters/entryKey"
    put:
      operationId: putEntry
      tags:
        - kv
      consumes:
        - application/octet-stream
      parameters:
        - name: If-Match
          in: header
          description: when this is an update to an entry, then this field needs to be present
          type: string
          pattern: "[0-9]*"
        - name: body
          in: body
          required: true
          schema:
            type: string
            format: binary
            maxLength: 536870912
      responses:
        201:
          description: entry was created
          headers:
            Location:
              description: the location to get the newly created entry
              type: string
              format: uri
            X-Request-Id:
              description: The request id this is a response to
              type: string
            Etag:
              description: The version of this entry
              type: string
        204:
          description: entry was updated
          headers:
            ETag:
              description: The version of this entry
              type: string
            X-Request-Id:
              description: The request id this is a response to
              type: string

        404:
          $ref: "#/responses/errorNotFound"

        409:
          description: there is a version mismatch for the entry
          headers:
            X-Request-Id:
              description: The request id this is a response to
              type: string
          schema:
            $ref: "#/definitions/error"

        410:
          description: The entry is deleted
          headers:
            X-Request-Id:
              description: The request id this is a response to
              type: string
          schema:
            $ref: '#/definitions/error'

        default:
          $ref: "#/responses/errorResponse"

    get:
      operationId: getEntry
      tags:
        - kv
      produces:
        - application/octet-stream
      parameters:
        - name: 'If-None-Match'
          in: header
          required: false
          type: string
      responses:
        200:
          description: entry was found
          headers:
            Last-Modified:
              description: The time this entry was last modified
              type: string
            X-Request-Id:
              description: The request id this is a response to
              type: string
            ETag:
              description: The version of this entry
              type: string
          schema:
            type: string
            format: binary
        304:
          description: entry was found but not modified
          headers:
            Last-Modified:
              description: The time this entry was last modified
              type: string
            X-Request-Id:
              description: The request id this is a response to
              type: string
            ETag:
              description: The version of this entry
              type: string
        404:
          $ref: "#/responses/errorNotFound"
        default:
          $ref: "#/responses/errorResponse"

    delete:
      operationId: deleteEntry
      tags:
        - kv
      responses:
        204:
          description: the delete was successful
          headers:
            X-Request-Id:
              description: The request id this is a response to
              type: string
        default:
          $ref: "#/responses/errorResponse"

definitions:
  error:
    description: |
      the error model is a model for all the error responses coming from kvstore
    type: object
    required:
      - message
      - code
    properties:
      code:
        type: integer
        format: int64
        description: The error code
      message:
        description: The error message
        type: string
      helpUrl:
        description: link to help page explaining the error in more detail
        type: string
        format: uri
      cause:
        $ref: '#/definitions/error'
